from .user import UserViewset
from .profesionviewset import ProfesionViewset
from .profesorviewset import ProfesorViewset
from .estudianteviewset import EstudianteViewset
from .nivelviewset import NivelViewset
from .seccionviewset import SeccionViewset
from .cursoviewset import CursoViewset
from .gradoviewset import GradoViewset
from .cicloescolarviewset import Ciclo_escolarViewset
from .asigancionviewset import AsignacionViewset
from .asignacionestudianteviewset import Asignacion_estudianteViewset
from .eventosviewset import EventosViewset
from .materialdeclaseviewset import Materiales_de_claseViewset
from .tareaviewset import TareaViewset
from .tareaestudianteviewset import TareasestudianteViewset