# Generated by Django 2.2.13 on 2021-05-12 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210507_1828'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarea',
            name='archivo',
            field=models.FileField(blank=True, null=True, upload_to='Tarea_catedraticos'),
        ),
        migrations.AlterField(
            model_name='tareasestudiante',
            name='archivo',
            field=models.FileField(blank=True, null=True, upload_to='Tarea_estudiantes'),
        ),
    ]
