# Generated by Django 2.2.13 on 2021-05-12 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20210512_0935'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarea',
            name='fecha_de_entrega',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='tarea',
            name='hora_de_entrega',
            field=models.TimeField(),
        ),
    ]
