from .profile import Profile
from .asignacion import Asignacion
from .asignacionestudiante import Asignacion_estudiante
from .cicloescolar import Ciclo_escolar
from .curso import Curso
from .estudiante import Estudiante
from .eventos import Eventos
from .grado import Grado
from .materialdeclase import Materiales_de_clase
from .nivel import Nivel
from .profesion import Profesion
from .profesor import Profesor
from .rol import Rol
from .seccion import Seccion
from .tarea import Tarea
from .tareasestudiante import Tareasestudiante